# Docs

# Label Config

# labeler:
#   - settings:
#     - codeOwnersPath: {PATH TO CODEOWNERS FILE (defaults to .github/CODEOWNERS)}
#   - labels:
#     - label: {YOUR LABEL NAME}
#       condition: {AND (default) | OR}
#       when:
#         {TEST_FUNCTION}: {REGEX}
#         ...
#     ...

#| Function Name               | Description                                                                |
#| --------------------------- | -------------------------------------------------------------------------- |
#| `isAnyFilePathMatch`        | Returns true if any filename in the PR diff matches the given regex        |
#| `isPRBodyMatch`             | Returns true if the PR description matches the given regex                 |
#| `isPRTitleMatch`            | Returns true if the PR title matches the given regex                       |
#| `isPRAuthorMatch`           | Returns true if the PR author matches the given regex                      |
#| `isPRAuthorCompanyMatch`    | Returns true if the PR author's company matches the given regex            |
#| `isAnyFileOwnedByMatch`     | Returns true if any owner of a file in the PR diff matches the given regex |
#| `isNotAnyFilePathMatch`     | The negation of `isAnyFilePathMatch`                                       |
#| `isNotPRBodyMatch`          | The negation of `isPRBodyMatch`                                            |
#| `isNotPRTitleMatch`         | The negation of `isPRTitleMatch`                                           |
#| `isNotPRAuthorMatch`        | The negation of `isPRAuthorMatch`                                          |
#| `isNotPRAuthorCompanyMatch` | The negation of `isPRAuthorCompanyMatch`                                   |
#| `isNotAnyFileOwnerByMatch`  | The negation of `isAnyFileOwnedByMatch`                                    |

labeler:
  labels:
    # created-by
    - label: "created-by: Fujinoki team"
      when:
        isPRAuthorMatch: "^(kijv)$"

    # needs: triage when not any of the Fujinoki team
    - label: "needs: triage"
      when:
        isNotPRAuthorMatch: "^(kijv)$"

    # areas
    - label: "area: ci"
      when:
        isAnyFilePathMatch: '^(\.github\/(workflows|actions).*|release.js)$'
    - label: "area: discord"
      when:
        isAnyFilePathMatch: '^(crates\/discord.*|packages\/discord.*)$'
    - label: "area: docs"
      when:
        isAnyFilePathMatch: '^(docs\/.*|README\.md)$'

    # type
    - label: "rust"
      when:
        isAnyFilePathMatch: '^((crates|xtask|.cargo)\/.*|(Cargo|deny|\.rustfmt|clippy|rust-toolchain).toml|.*\.rs)$'
    - label: "js"
      when:
        isAnyFilePathMatch: '^(packages\/.*|package\.json|pnpm-workspace\.yaml|.*\.(t|j)s)$'

    # release
    - label: "release: fujinoki"
      when:
        isAnyFilePathMatch: '^version\.txt$'
        isPRTitleMatch: '^release\(fujinoki\):.*$'
