[build]
rustflags = [
  "--cfg",
  "tokio_unstable",
  "-Zshare-generics=y", # make the current crate share its generic instantiations
  "-Zthreads=8", # parallel frontend https://blog.rust-lang.org/2023/11/09/parallel-rustc.html
  "-Csymbol-mangling-version=v0",
]
rustdocflags = []

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"

[target.aarch64-pc-windows-msvc]
linker = "rust-lld"

[alias]
xtask = "run --bin xtask"
fn-build = "build --bin fujinoki-cli"
fn-run = "run --bin fujinoki-cli"
# Builds all test code to check for compiler errors before running
fn-pre-test = "nextest run --no-run --workspace --release"
fn-test = "nextest run --workspace --release --no-fail-fast"
fn-bench-test = "test --benches --workspace --release --no-fail-fast"
fn-check = "check --workspace"
fn-clippy = "clippy --workspace"

[target.'cfg(all())']
rustflags = [
  "--cfg",
  "tokio_unstable",
  "-Zshare-generics=y",
  "-Csymbol-mangling-version=v0",
]

