// prettier-ignore
/* eslint-disable */
/* auto-generated by NAPI-RS */

const { readFileSync } = require('fs')

let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  const report = typeof process.report.getReport === 'function' ? process.report.getReport() : null
  if (!report) {
    return null
  }
  if (report.header?.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      REQUIRE_TUPLE('android-arm64')
    } else if (process.arch === 'arm') {
      REQUIRE_TUPLE('android-arm-eabi')
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      REQUIRE_TUPLE('win32-x64-msvc')
    } else if (process.arch === 'ia32') {
      REQUIRE_TUPLE('win32-ia32-msvc')
    } else if (process.arch === 'arm64') {
      REQUIRE_TUPLE('win32-arm64-msvc')
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    REQUIRE_TUPLE('darwin-universal')
    if (process.arch === 'x64') {
      REQUIRE_TUPLE('darwin-x64')
    } else if (process.arch === 'arm64') {
      REQUIRE_TUPLE('darwin-arm64')
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      REQUIRE_TUPLE('freebsd-x64')
    } else if (process.arch === 'arm64') {
      REQUIRE_TUPLE('freebsd-arm64')
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        REQUIRE_TUPLE('linux-x64-musl')
      } else {
        REQUIRE_TUPLE('linux-x64-gnu')
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        REQUIRE_TUPLE('linux-arm64-musl')
      } else {
        REQUIRE_TUPLE('linux-arm64-gnu')
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        REQUIRE_TUPLE('linux-arm-musleabihf')
      } else {
        REQUIRE_TUPLE('linux-arm-gnueabihf')
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        REQUIRE_TUPLE('linux-riscv64-musl')
      } else {
        REQUIRE_TUPLE('linux-riscv64-gnu')
      }
    } else if (process.arch === 'ppc64') {
      REQUIRE_TUPLE('linux-ppc64-gnu')
    } else if (process.arch === 's390x') {
      REQUIRE_TUPLE('linux-s390x-gnu')
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  try {
    nativeBinding = require('./{localName}.wasi.cjs')
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      loadErrors.push(err)
    }
  }
  if (!nativeBinding) {
    try {
      nativeBinding = require('{pkgName}-wasm32-wasi')
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        loadErrors.push(err)
      }
    }
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    // TODO Link to documentation with potential fixes
    //  - The package owner could build/publish bindings for this arch
    //  - The user may need to bundle the correct files
    //  - The user may need to re-install node_modules to get new packages
    throw new Error('Failed to load native binding', { cause: loadErrors })
  }
  throw new Error('Failed to load native binding')
}

IDENTS
