[package]
name = "discord-api-napi"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[features]
default = ["custom_allocator", "rustls-tls"]
native-tls = ["discord-api/native-tls"]
rustls-tls = ["discord-api/rustls-tls"]
custom_allocator = ["turbopack-binding/__turbo_tasks_malloc"]

[dependencies]
napi = { version = "2", features = ["async", "tokio_rt", "serde-json"] }
napi-derive = "2"
paste = "1"

anyhow = { workspace = true, features = ["backtrace"] }
discord-api = { workspace = true }
turbopack-binding = { workspace = true, features = [
  "__turbo_tasks",
  "__turbo_tasks_fs",
  "__turbo_tasks_malloc",
  "__turbo_tasks_memory",
] }
serde_json = { workspace = true }

[build-dependencies]
napi-build = "2"
turbopack-binding = { workspace = true, features = ["__turbo_tasks_build"] }
