name: Code quality

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  actions: write
  contents: read
  pull-requests: read

jobs:
  optimize_ci:
    name: Optimize CI
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_skip.outputs.skip }}
    steps:
      - name: Optimize CI
        id: check_skip
        uses: withgraphite/graphite-ci-action@main
        with:
          graphite_token: ${{ secrets.GRAPHITE_TOKEN }}

  determine_jobs:
    name: Determine jobs to run
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    needs: optimize_ci
    if: needs.optimize_ci.outputs.skip == 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CI related changes
        id: ci
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            .github/actions/**
            .github/workflows/code-quality.yml

      - name: Rust related changes
        id: rust
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            pnpm-lock.yaml
            package.json
            Cargo.**
            crates/**
            .cargo/**
            rust-toolchain.toml
            !**.md
            !**.mdx

      - name: PR with rust label
        id: rust_label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: context.head_ref,
              base: 'main',
              state: 'open',
            });
            return pullRequests.filter(pr => pr.labels.map(label => label.name).includes('rust')).length > 0;

      - name: Biome linter related changes
        id: biome
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.{js,jsx,ts,tsx,json,jsonc,css,graphql,yaml,yml,html}

    outputs:
      rust: ${{ steps.ci.outputs.diff != '' || steps.rust.outputs.diff != '' || steps.rust_label.outputs.result == 'true' }}
      biome: ${{ steps.ci.outputs.diff != '' || steps.biome.outputs.diff != '' }}

  rust_lint:
    needs: [determine_jobs]
    if: needs.determine_jobs.outputs.rust == 'true'
    name: Rust lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: ./.github/actions/setup-rust

      - name: Run cargo fmt check
        run: |
          cargo fmt --check

      - name: Check Cargo.toml formatting (taplo)
        run: npx @taplo/cli@0.5.2 format --check

  biome_lint:
    name: Biome Lint
    runs-on: ubuntu-latest
    needs: determine_jobs
    if: needs.determine_jobs.outputs.biome == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Linter
        run: biome ci . --reporter=github --formatter-enabled=false

      - name: Formatter
        # keep this in sync with package.json (biome:format)
        run: biome check --linter-enabled=false --organize-imports-enabled=true
