name: Publish npm packages

# TODO uncomment
# on:
#   push:
#     branches: [main]

jobs:
  publish-npm:
    # xtask/src/publish.rs:558
    if: "startsWith(github.event.head_commit.message, 'chore: release npm packages')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-rust

      - name: Build packages
        run: pnpx turbo@canary run build:ts

      - name: Write NPM_TOKEN
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN_ELEVATED }}" > ~/.npmrc

      - name: Publish
        run: cargo xtask workspace --publish
