name: Update turbopack/turborepo bindings

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  turbopack-changed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Parse current SHA from Cargo.toml
        id: parse-sha
        run: |
          CURRENT_SHA=$(cat crates/turbopack-binding/Cargo.toml | grep -A 1 'package.metadata' | grep 'rev' | awk -F ' = ' '{print $2}' | tr -d '"')
          echo "current_sha=$CURRENT_SHA" >> $GITHUB_OUTPUT
        shell: bash
      - id: get-latest-sha
        uses: ./.github/actions/repo-sha
        with:
          repo: kijv/next.js
          branch: canary

      - name: Compare SHAs
        id: compare-sha
        run: |
          if [ "${{ steps.get-latest-sha.outputs.sha }}" != "${{ steps.parse-sha.outputs.current_sha }}" ]; then
            echo "sha_changed=true" >> $GITHUB_OUTPUT
            echo "new_sha=${{ steps.get-latest-sha.outputs.sha }}" >> $GITHUB_OUTPUT
          else
            echo "sha_changed=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Check if path has changed
        id: check-path
        shell: bash
        if: ${{ steps.compare-sha.outputs.sha-changed == 'true' }}
        run: |
          if git diff-tree ${{ steps.get-latest-sha.outputs.sha }} ${{ steps.parse-sha.outputs.current_sha }} --no-commit-id --name-only -r -p | grep 'turbopack/.*/.*'; then
            echo "path_changed=true" >> $GITHUB_OUTPUT
          else
            echo "path_changed=false" >> $GITHUB_OUTPUT

      - name: Check if Cargo.toml has changed
        id: check-cargo-toml
        if: ${{ steps.compare-sha.outputs.sha-changed == 'true' }}
        run: |
          if git diff-tree ${{ steps.get-latest-sha.outputs.sha }} ${{ steps.parse-sha.outputs.current_sha }} --no-commit-id --name-only -r -p | grep 'Cargo.toml'; then
            echo "cargo_toml_changed=true" >> $GITHUB_OUTPUT
          else
            echo "cargo_toml_changed=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Parse Cargo.toml
        id: parse-cargo-toml
        if: ${{ steps.check-cargo-toml.outputs.cargo_toml_changed == 'true' }}
        run: |
          SWC_CORE=$(grep -A 5 'swc_core =' Cargo.toml | sed -n '/^swc_core = {/,/}/p')
          TESTING=$(grep -A 1 '[workspaces.dependencies]' Cargo.toml | grep 'testing = { version')
          echo "crate_swc_core=$SWC_CORE" >> $GITHUB_OUTPUT
          echo "crate_testing=$TESTING" >> $GITHUB_OUTPUT
        shell: bash

      - name: Output Cargo.toml changes
        if: ${{ steps.check-cargo-toml.outputs.cargo_toml_changed == 'true' }}
        run: |
          echo "Cargo.toml changed: true"
          echo "swc_core version: ${{ steps.parse-cargo-toml.outputs.swc_core_version }}"
          echo "testing version: ${{ steps.parse-cargo-toml.outputs.testing_version }}"
        shell: bash

      - name: Output result
        run: |
          echo "SHA changed: ${{ steps.compare-sha.outputs.sha-changed }}"
          if [ "${{ steps.compare-sha.outputs.sha-changed }}" == "true" ]; then
            echo "New SHA: ${{ steps.compare-sha.outputs.new_sha }}"
          fi
        shell: bash

      # git changes so we need to checkout again or else post local actions will fail
      - uses: actions/checkout@v3
    outputs:
      crate_swc_core: ${{ steps.parse-cargo-toml.outputs.crate_swc_core }}
      crate_testing: ${{ steps.parse-cargo-toml.outputs.crate_testing }}
      path-changed: ${{ steps.check-path.outputs.path_changed || 'false' }}
      sha-changed: ${{ steps.compare-sha.outputs.sha_changed }}
      current-sha: ${{ steps.parse-sha.outputs.current_sha }}
      new-sha: ${{ steps.compare-sha.outputs.new_sha }}

  turborepo-changed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Parse current SHA from Cargo.toml
        id: parse-sha
        run: |
          CURRENT_SHA=$(cat crates/turborepo-binding/Cargo.toml | grep -A 1 'package.metadata' | grep 'rev' | awk -F ' = ' '{print $2}' | tr -d '"')
          echo "current_sha=$CURRENT_SHA" >> $GITHUB_OUTPUT
          echo "Current SHA: $CURRENT_SHA"

      - id: get-latest-sha
        uses: ./.github/actions/repo-sha
        with:
          repo: kijv/turborepo
          branch: main

      - name: Compare SHAs
        id: compare-sha
        run: |
          if [ "${{ steps.get-latest-sha.outputs.sha }}" != "${{ steps.parse-sha.outputs.current_sha }}" ]; then
            echo "sha_changed=true" >> $GITHUB_OUTPUT
            echo "new_sha=${{ steps.get-latest-sha.outputs.sha }}" >> $GITHUB_OUTPUT
          else
            echo "sha_changed=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Output result
        run: |
          echo "SHA changed: ${{ steps.compare-sha.outputs.sha-changed || 'false' }}"
          if [ "${{ steps.compare-sha.outputs.sha-changed }}" == "true" ]; then
            echo "New SHA: ${{ steps.compare-sha.outputs.new_sha }}"
          fi
        shell: bash

      # git changes so we need to checkout again or else post local actions will fail
      - uses: actions/checkout@v3
    outputs:
      sha-changed: ${{ steps.compare-sha.outputs.sha_changed }}
      current-sha: ${{ steps.parse-sha.outputs.current_sha }}
      new-sha: ${{ steps.compare-sha.outputs.new_sha }}

  update-bindings:
    runs-on: ubuntu-latest
    needs: [turbopack-changed, turborepo-changed]
    if: ${{ needs.turbopack-changed.outputs.sha-changed == 'true' || needs.turborepo-changed.outputs.sha-changed == 'true' }}
    steps:
      - if: ${{ needs.turbopack-changed.outputs.sha-changed == 'true' && needs.turbopack-changed.outputs.path-changed == 'false' }}
        run: |
          echo "Next.js repo changed but files in `turbopack` directory have not changed; skipping update"
        shell: bash

      - name: Update Turbopack binding in Cargo.toml
        if: ${{ needs.turbopack-changed.outputs.path-changed == 'true' }}
        run: |
          sed -i '' 's/rev = "${{ needs.turbopack-changed.outputs.current-sha }}"/rev = "${{ needs.turbopack-changed.outputs.new-sha }}"/g' crates/turbopack-binding/Cargo.toml
          sed -i '' 's/swc_core = {[^}]*}\n/${{ needs.turbopack-changed.outputs.crate_swc_core }}/g' crates/turbopack-binding/Cargo.toml
          sed -i '' 's/testing = {[^}]*}/${{ needs.turbopack-changed.outputs.crate_testing }}/g' crates/turbopack-binding/Cargo.toml
          echo "Updated Turbopack binding in crates/turbopack-binding/Cargo.toml"
        shell: bash

      - name: Update Turborepo binding in Cargo.toml
        if: ${{ needs.turborepo-changed.outputs.sha-changed == 'true' }}
        run: |
          sed -i '' 's/rev = "${{ needs.turbopack-changed.outputs.current-sha }}"/rev = "${{ needs.turbopack-changed.outputs.new-sha }}"/g' crates/turborepo-binding/Cargo.toml
          echo "Updated Turborepo binding in crates/turborepo-binding/Cargo.toml"
        shell: bash

      - name: Create branch
        id: branch
        run: |
          if [[ "${{ needs.turbopack-changed.outputs.path-changed == 'true' }}" == "true" && "${{ needs.turborepo-changed.outputs.sha-changed }}" == "true" ]]; then
            branch_name="update-bindings-${{ needs.turbopack-changed.outputs.new-sha }}-${{ needs.turborepo-changed.outputs.new-sha }}"
          elif [[ "${{ needs.turbopack-changed.outputs.path-changed == 'true' }}" == "true" ]]; then
            branch_name="update-turbopack-${{ needs.turbopack-changed.outputs.new-sha }}"
          elif [[ "${{ needs.turborepo-changed.outputs.sha-changed }}" == "true" ]]; then
            branch_name="update-turborepo-${{ needs.turborepo-changed.outputs.new-sha }}"
          else
            echo "No changes detected. Exiting."
            exit 0
          fi
          git checkout -b "$branch_name"
          echo "$branch_name" >> $GITHUB_OUTPUT

      - name: Stage changes
        if: ${{ needs.turbopack-changed.outputs.path-changed == 'true' || needs.turborepo-changed.outputs.sha-changed == 'true' }}
        run: |
          git config --global user.name 'jujutsu bot'
          git config --global user.email 'bot@jujutsu.studio'
          git add crates/turbopack-binding/Cargo.toml crates/turborepo-binding/Cargo.toml
          git commit -m "chore: update turbopack/turborepo bindings"
          git push --force --set-upstream origin "${{ steps.branch.outputs.branch_name }}"
    outputs:
      stage-branch: ${{ steps.branch.outputs.branch_name }}

  open-pr:
    name: Open PR
    needs: [update-bindings]
    if: ${{ needs.update-bindings.outputs.stage-branch != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1.0.0
        with:
          ref: ${{ needs.update-bindings.outputs.stage-branch }}

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ needs.update-bindings.outputs.stage-branch }}
          base: main
          title: "chore: update turbopack/turborepo bindings"
