name: Update forks of turborepo/next.js

on:
  schedule:
    - cron: '0 0 * * 0'  # Run every week
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-forks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Get latest SHAs
        id: get-shas
        run: |
          echo "NEXT_SHA=$(git ls-remote https://github.com/vercel/next.js.git HEAD | cut -f1)" >> $GITHUB_OUTPUT
          echo "TURBO_SHA=$(git ls-remote https://github.com/vercel/turborepo.git HEAD | cut -f1)" >> $GITHUB_OUTPUT

      - name: Check for changes in Next.js
        id: next-changes
        run: |
          git clone https://github.com/kijv/next.js.git
          cd next.js
          git remote add upstream https://github.com/vercel/next.js.git
          git fetch upstream
          DIFF=$(git diff HEAD...${{ steps.get-shas.outputs.NEXT_SHA }} --name-only)
          if [ -n "$DIFF" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "diff=$DIFF" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for changes in Turborepo
        id: turbo-changes
        run: |
          git clone https://github.com/kijv/turborepo.git
          cd turborepo
          git remote add upstream https://github.com/vercel/turborepo.git
          git fetch upstream
          DIFF=$(git diff HEAD...${{ steps.get-shas.outputs.TURBO_SHA }} --name-only)
          if [ -n "$DIFF" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "diff=$DIFF" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Update Next.js fork and create/update PR
        if: steps.next-changes.outputs.changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.BINDINGS_PAT }}
        run: |
          cd next.js
          git checkout -b update-next-js
          git pull upstream canary
          git push -f origin update-next-js
          PR_URL=$(gh pr list --head update-next-js --json url --jq '.[0].url')
          if [ -n "$PR_URL" ]; then
            gh pr edit $PR_URL --body "Updated diff:
          ${{ steps.next-changes.outputs.diff }}"
          else
            gh pr create --title "Update Next.js fork" --body "Changes:
          ${{ steps.next-changes.outputs.diff }}" --base main
          fi

      - name: Update Turborepo fork and create/update PR
        if: steps.turbo-changes.outputs.changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.BINDINGS_PAT }}
        run: |
          cd turborepo
          git checkout -b update-turborepo
          git pull upstream main
          git push -f origin update-turborepo
          PR_URL=$(gh pr list --head update-turborepo --json url --jq '.[0].url')
          if [ -n "$PR_URL" ]; then
            gh pr edit $PR_URL --body "Updated diff:
          ${{ steps.turbo-changes.outputs.diff }}"
          else
            gh pr create --title "Update Turborepo fork" --body "Changes:
          ${{ steps.turbo-changes.outputs.diff }}" --base main
          fi

      - name: Update Turbopack (Next.js) fork and create/update PR
        if: steps.next-changes.outputs.changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.BINDINGS_PAT }}
        run: |
          cd next.js
          git checkout -b update-next-js
          git pull upstream canary
          git push -f origin update-next-js
          PR_URL=$(gh pr list --head update-next-js --json url --jq '.[0].url')
          if [ -n "$PR_URL" ]; then
            gh pr edit $PR_URL --body "Updated diff:
          ${{ steps.next-changes.outputs.diff }}"
          else
            gh pr create --title "Update Next.js fork" --body "Changes:
          ${{ steps.next-changes.outputs.diff }}" --base main
          fi
